# vim: ft=ruby
PKG_VERSION = '0.9.2'
spec = Gem::Specification.new do |s|
  s.name = 'icu'
  s.version = PKG_VERSION
  s.authors = ['Joshua Llorach', "Rich Healey"]
  s.email = 'richard.healey@99designs.com'
  s.homepage = 'http://github.com/99designs/icu'
  s.platform = Gem::Platform::RUBY
  s.summary = 'International Components for Unicode for Ruby'
  s.files = Dir['{ext,lib,test}/**/*'].to_a << 'COPYING' << 'COPYING.LESSER'
  s.require_path = 'lib'
  s.autorequire = 'icu'
  s.extensions = ['ext/extconf.rb']
  s.test_files = Dir['{test}/**/*'].to_a
  s.has_rdoc = true
  s.extra_rdoc_files = ['README.md']
  s.rubyforge_project = 'icu'
end
